In [10]:
# !pip install spacy-stanza

In [6]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [7]:
import pandas as pd

In [8]:
import stanza
from spacy_stanza import StanzaLanguage
from spacy import displacy
stanza.download('sv')

import spacy.lang.sv.stop_words as sv_stop_words

2021-01-16 10:03:57 INFO: Downloading default packages for language: sv (Swedish)...
2021-01-16 10:03:57 INFO: File exists: /Users/test/stanza_resources/sv/default.zip.
2021-01-16 10:03:59 INFO: Finished downloading models and saved to /Users/test/stanza_resources.


In [9]:
snlp = stanza.Pipeline(lang="sv")
nlp = StanzaLanguage(snlp)

2021-01-16 10:03:59 INFO: Loading these models for language: sv (Swedish):
| Processor | Package   |
-------------------------
| tokenize  | talbanken |
| pos       | talbanken |
| lemma     | talbanken |
| depparse  | talbanken |

2021-01-16 10:03:59 INFO: Use device: cpu
2021-01-16 10:03:59 INFO: Loading: tokenize
2021-01-16 10:04:00 INFO: Loading: pos
2021-01-16 10:04:00 INFO: Loading: lemma
2021-01-16 10:04:00 INFO: Loading: depparse
2021-01-16 10:04:02 INFO: Done loading processors!


In [11]:
text = """Många läsare utanför Stockholm blir irriterade på vad de upplever som för stort Stockholmsfokus på DN.se för 15 gånger. Samtidigt tycker våra läsare i Stockholm att vi har för lite Stockholmsnyheter på startsidan. Med satsningen på Göteborg blev detta en av våra viktigaste utmaningar att lösa, säger Anna Åberg."""
doc = nlp(text)
doc

Många läsare utanför Stockholm blir irriterade på vad de upplever som för stort Stockholmsfokus på DN.se för 15 gånger. Samtidigt tycker våra läsare i Stockholm att vi har för lite Stockholmsnyheter på startsidan. Med satsningen på Göteborg blev detta en av våra viktigaste utmaningar att lösa, säger Anna Åberg.

In [12]:
for token in doc:
    print( "  TEXT:", token.text, "  LEMMA:", token.lemma_, "  POS:", token.pos_, "  DEPEND:", token.dep_, "  ENTITY:", token.ent_type_, "  STOP_WORD:", token.is_stop, "  NUMBER:", token.like_num)
    

  TEXT: Många   LEMMA: många   POS: ADJ   DEPEND: amod   ENTITY:    STOP_WORD: True   NUMBER: False
  TEXT: läsare   LEMMA: läsare   POS: NOUN   DEPEND: nsubj:pass   ENTITY:    STOP_WORD: False   NUMBER: False
  TEXT: utanför   LEMMA: utanför   POS: ADP   DEPEND: case   ENTITY:    STOP_WORD: True   NUMBER: False
  TEXT: Stockholm   LEMMA: Stockholm   POS: PROPN   DEPEND: nmod   ENTITY:    STOP_WORD: False   NUMBER: False
  TEXT: blir   LEMMA: bli   POS: AUX   DEPEND: aux:pass   ENTITY:    STOP_WORD: True   NUMBER: False
  TEXT: irriterade   LEMMA: irritera   POS: VERB   DEPEND: root   ENTITY:    STOP_WORD: False   NUMBER: False
  TEXT: på   LEMMA: på   POS: ADP   DEPEND: mark   ENTITY:    STOP_WORD: True   NUMBER: False
  TEXT: vad   LEMMA: vad   POS: PRON   DEPEND: obj   ENTITY:    STOP_WORD: True   NUMBER: False
  TEXT: de   LEMMA: de   POS: PRON   DEPEND: nsubj   ENTITY:    STOP_WORD: True   NUMBER: False
  TEXT: upplever   LEMMA: uppleva   POS: VERB   DEPEND: advcl   ENTITY:    STO

In [14]:
displacy.render(doc, jupyter=True)

### Read the JSON. file

In [70]:
import json

data = None
with open('newsItemList_2020-12-31.json') as json_file:
    data = json.load(json_file)
    # print(data)

data2 = None
with open('newsItemList_2021-01-12T21-00-03.json') as json_file:
    data2 = json.load(json_file)

data3 = None
with open('newsItemList_2021-01-13T01-00-02.json') as json_file:
    data3 = json.load(json_file)

    
    
# data[0]
# " ".join(data[0]['Tokens'])



In [76]:
len(data) + len(data2) + len(data3)
data.extend(data2)
data.extend(data3)
len(data)

232

232

### Check all or indevidual document metadata with stanza lib

In [77]:
%%time
pd.set_option('display.max_rows', 1000)
df_doc = pd.DataFrame()

for item in data[:10]:
    news_text = " ".join(item['Tokens'])
    # print(news_text)
    s_doc = nlp(news_text)
    
    for token in s_doc[:]:
        # print( "  TEXT:", token.text, "  LEMMA:", token.lemma_, "  POS:", token.pos_, "  DEPEND:", token.dep_, "  ENTITY:", token.ent_type_, "  STOP_WORD:", token.is_stop, "  NUMBER:", token.like_num)
        dict_sent = {
              "TEXT": token.text, 
              "LEMMA": token.lemma_, 
              "POS": token.pos_, 
              "DEPEND": token.dep_, 
              "ENTITY": token.ent_type_, 
              "STOP_WORD": token.is_stop, 
              "NUMBER": token.like_num
        }
        df_doc = df_doc.append(dict_sent, ignore_index=True)
    

    
df_doc[:]
# df_doc[df_doc['POS'] == 'NUM']
# df_doc[df_doc['DEPEND'] == 'punct'] # [:10]

    
    


CPU times: user 36.5 s, sys: 1.43 s, total: 38 s
Wall time: 15.3 s


DEPEND ENTITY       LEMMA  NUMBER    POS  STOP_WORD          TEXT
0       case              [CLS]     0.0    ADP        0.0         [CLS]
1        obl         nyårsafton     0.0   NOUN        0.0  Nyårsaftonen
2     nummod               2006     1.0    NUM        0.0          2006
3       root            förlora     0.0   VERB        0.0     förlorade
4      nsubj            Sverige     0.0  PROPN        0.0       Sverige
...      ...    ...         ...     ...    ...        ...           ...
1918    case                 av     0.0    ADP        1.0            av
1919   punct                  .     0.0  PUNCT        0.0             .
1920    case                  [     0.0    SYM        0.0             [
1921    root                SEP     0.0   NOUN        0.0           SEP
1922   punct                  ]     0.0  PUNCT        0.0             ]

[1923 rows x 7 columns]

### Process single document

In [78]:

# data[0]['Tokens']
single_newsItem_tokens = data[0]['Tokens']

# Remove BERT tokens
cln_tokens = [t for t in single_newsItem_tokens if t!='[CLS]' if t!='[SEP]']
# cln_tokens

# Convert to stanza library doc
document = " ".join(cln_tokens)
s_doc = nlp(document)

# Remove punctuations
rp_doc = [t for t in s_doc if t.dep_ != 'punct']
# rp_doc

# Remove stop-words
rs1_doc = [t for t in rp_doc if t not in sv_stop_words.STOP_WORDS]
rs_doc = [t for t in rs1_doc if not t.is_stop]
#rs_doc

# Remove number
rn_doc = [t for t in rs_doc if t.pos_ != 'NUM']

# Select only lemma and lower-case
processed_sentence = " ".join([t.lemma_.lower() for t in rn_doc])
processed_sentence




'nyårsafton förlora sverige usa gruppspelsmatchen följa rak svensk seger gruppspelsmatcher junior - vm juniorkrona natt nyårsafton förlora ryssland förlängning år jvm - turnering edmonton återstå gruppspelsmatch svensk junior matchen start ny segersvit seger usa natt match innebära betydlig enkel svensk motstånd kvartsfinal vara spelare år år junia vm svensk spel oavsett årgång egentligen speciell förhållande omtala omskriva segersviten märka tydlig juniorkrona förbundskapt philip broberg pressträffare edmonton gång gång kapt broberg upprepa hända gruppspel spela roll sverige vara edmonton ta guld vara snarare omvärld häpna makalösa svit matchen usa hända gruppspel betydelse usa oavsett ske ordinari tid förlängning innebära juniorkrona möta slovakien kvartsfinal slovakien visserligen match kanada förlust förlust finland synas lag brist tydlig svensk förlust usa ställa sverige istället segrare natt match kanada finland lag kalla drömmotståndare väg gruppfinal lag vinna samtlig matcher s

## Process multi-document
### Create pandas df from data

In [79]:
data[0]['Tokens'][:5]
tokens_list = [item['Tokens'] for item in data ]
newsId_list = [item['NewsID'] for item in data ]


['[CLS]', 'Nyårsaftonen', '2006', 'förlorade', 'Sverige']

In [80]:
news_items_pdf = pd.DataFrame({
    'TOKENS':tokens_list,
    'NEWSID':newsId_list,
})

In [81]:
news_items_pdf.head()

TOKENS  \
0  [[CLS], Nyårsaftonen, 2006, förlorade, Sverige...   
1  [[CLS], Fastigheten, på, Hiselsvägen, 4, i, Öj...   
2  [[CLS], Fastigheten, på, Rånäsvägen, 18, i, Sm...   
3  [[CLS], Sedan, 02, -, tiden, natten, mot, tors...   
4  [[CLS], På, årets, sista, dag, gav, sig, NA, u...   

                                 NEWSID  
0  b0332648-6645-4b59-a48b-7bdcfe0e34f0  
1  3e49c41a-6116-4675-8fa3-c48c10073740  
2  28933d5d-07d6-46b0-abef-99ac6fb7c154  
3  b3102586-a6b2-4f47-b0fc-1e79ca602317  
4  2bd8bc33-c860-418e-b538-4d77d8659f0e

### Define text processing function

In [82]:
def process_document(single_newsItem_tokens):

    # data[0]['Tokens']
    # single_newsItem_tokens = data[0]['Tokens']

    # Remove BERT tokens
    cln_tokens = [t for t in single_newsItem_tokens if t!='[CLS]' if t!='[SEP]']
    # cln_tokens

    # Convert to stanza library doc
    document = " ".join(cln_tokens)
    s_doc = nlp(document)

    # Remove punctuations
    rp_doc = [t for t in s_doc if t.dep_ != 'punct']
    # rp_doc

    # Remove stop-words
    rs1_doc = [t for t in rp_doc if t not in sv_stop_words.STOP_WORDS]
    rs_doc = [t for t in rs1_doc if not t.is_stop]
    # rp_doc

    # Remove number
    rn_doc = [t for t in rs_doc if t.pos_ != 'NUM']

    # Select only lemma and lower-case
    processed_sentence = " ".join([t.lemma_.lower() for t in rn_doc])
    return processed_sentence


In [83]:
from tqdm import trange, tqdm
# from tqdm.notebook import tqdm


In [84]:
tqdm().pandas()
news_items_pdf['ProcessedNews'] = news_items_pdf['TOKENS'].progress_apply(process_document) 

0it [00:00, ?it/s]
/Users/test/.local/share/virtualenvs/Deeplearn-9o849f8l/lib/python3.7/site-packages/tqdm/std.py:668: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
100%|██████████| 232/232 [04:05<00:00,  1.06s/it]


In [85]:
news_items_pdf.head() 
news_items_pdf['ProcessedNews'][0]

TOKENS  \
0  [[CLS], Nyårsaftonen, 2006, förlorade, Sverige...   
1  [[CLS], Fastigheten, på, Hiselsvägen, 4, i, Öj...   
2  [[CLS], Fastigheten, på, Rånäsvägen, 18, i, Sm...   
3  [[CLS], Sedan, 02, -, tiden, natten, mot, tors...   
4  [[CLS], På, årets, sista, dag, gav, sig, NA, u...   

                                 NEWSID  \
0  b0332648-6645-4b59-a48b-7bdcfe0e34f0   
1  3e49c41a-6116-4675-8fa3-c48c10073740   
2  28933d5d-07d6-46b0-abef-99ac6fb7c154   
3  b3102586-a6b2-4f47-b0fc-1e79ca602317   
4  2bd8bc33-c860-418e-b538-4d77d8659f0e   

                                       ProcessedNews  
0  nyårsafton förlora sverige usa gruppspelsmatch...  
1  fastighet hiselsvägen öje ny ägare köpare vara...  
2  fastighet rånäsvägen smedjebacken ny ägare tom...  
3  tid natt torsdag strömavbrott pågå ellevios el...  
4  år ge na regn höra örebro se gång år förhoppni...

'nyårsafton förlora sverige usa gruppspelsmatchen följa rak svensk seger gruppspelsmatcher junior - vm juniorkrona natt nyårsafton förlora ryssland förlängning år jvm - turnering edmonton återstå gruppspelsmatch svensk junior matchen start ny segersvit seger usa natt match innebära betydlig enkel svensk motstånd kvartsfinal vara spelare år år junia vm svensk spel oavsett årgång egentligen speciell förhållande omtala omskriva segersviten märka tydlig juniorkrona förbundskapt philip broberg pressträffare edmonton gång gång kapt broberg upprepa hända gruppspel spela roll sverige vara edmonton ta guld vara snarare omvärld häpna makalösa svit matchen usa hända gruppspel betydelse usa oavsett ske ordinari tid förlängning innebära juniorkrona möta slovakien kvartsfinal slovakien visserligen match kanada förlust förlust finland synas lag brist tydlig svensk förlust usa ställa sverige istället segrare natt match kanada finland lag kalla drömmotståndare väg gruppfinal lag vinna samtlig matcher s

### Count vectorize

In [86]:
import matplotlib.pyplot as plt
from sklearn.decomposition import NMF, LatentDirichletAllocation, TruncatedSVD
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.manifold import TSNE
import numpy as np


In [87]:
vectorizer = CountVectorizer(min_df=5, max_df=0.95, lowercase=True)
data_vectorized = vectorizer.fit_transform(news_items_pdf['ProcessedNews'])

print(f"Number if news items: {len(news_items_pdf['ProcessedNews'])}")
print("Output Vector Shape: ", data_vectorized.shape)

Number if news items: 232
Output Vector Shape:  (232, 1040)


In [88]:
print(f"Features for the vocabulary: {len(vectorizer.get_feature_names())}\n*", "* " * 15)
np.array(vectorizer.get_feature_names())

Features for the vocabulary: 1040
* * * * * * * * * * * * * * * * 


array(['affär', 'aftonbladet', 'agera', ..., 'östersund', 'överraska',
       'övrig'], dtype='<U19')

In [89]:
print(f'Vocabulary count: {len(vectorizer.vocabulary_)}')
print ( '-- ' * 7)
print(vectorizer.vocabulary_)

Vocabulary count: 1040
-- -- -- -- -- -- -- 
{'nyårsafton': 573, 'förlora': 259, 'sverige': 816, 'usa': 937, 'följa': 249, 'svensk': 815, 'vm': 990, 'natt': 555, 'ryssland': 700, 'år': 1023, 'matchen': 507, 'ny': 568, 'innebära': 363, 'betydlig': 89, 'vara': 961, 'spelare': 780, 'spel': 778, 'oavsett': 584, 'egentligen': 184, 'speciell': 777, 'märka': 543, 'tydlig': 906, 'gång': 296, 'hända': 334, 'spela': 779, 'roll': 692, 'ta': 843, 'guld': 294, 'snarare': 766, 'ske': 744, 'tid': 861, 'möta': 552, 'synas': 825, 'lag': 454, 'brist': 104, 'ställa': 805, 'istället': 380, 'kalla': 395, 'väg': 991, 'vinna': 983, 'samtlig': 724, 'släppa': 760, 'mål': 546, 'hävda': 339, 'klara': 405, 'slå': 761, 'resa': 676, 'tanke': 852, 'kosta': 432, 'säker': 827, 'resultera': 682, 'hel': 304, 'positiv': 639, 'se': 727, 'öga': 1032, 'steg': 793, 'ansvarig': 32, 'tomas': 880, 'testa': 857, 'covid': 128, 'visa': 986, 'låta': 491, 'ge': 277, 'resultat': 681, 'däremot': 171, 'chans': 120, 'enda': 189, 'fastig

In [90]:
# Our final vector:
print('Full vector: ')
print(data_vectorized.toarray())


Full vector: 
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 1 0]
 [0 1 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]]


In [91]:
np.isnan(data_vectorized.toarray()).any()
np.isinf(data_vectorized.toarray()).any()

# [np.isnan(a).any() for a in  data_vectorized.toarray()]

False

False

### Implement LDA

In [92]:
NUM_TOPICS = 10

In [93]:
# Latent Dirichlet Allocation Model
lda = LatentDirichletAllocation(n_components=NUM_TOPICS, max_iter=10, learning_method='online',verbose=True)
data_lda = lda.fit_transform(data_vectorized)

iteration: 1 of max_iter: 10
iteration: 2 of max_iter: 10
iteration: 3 of max_iter: 10
iteration: 4 of max_iter: 10
iteration: 5 of max_iter: 10
iteration: 6 of max_iter: 10
iteration: 7 of max_iter: 10
iteration: 8 of max_iter: 10
iteration: 9 of max_iter: 10
iteration: 10 of max_iter: 10


In [94]:
# Functions for printing keywords for each topic
def selected_topics(model, vectorizer, top_n=10):
    for idx, topic in enumerate(model.components_):
        print("Topic %d:" % (idx))
        print([(vectorizer.get_feature_names()[i], topic[i])
                        for i in topic.argsort()[:-top_n - 1:-1]]) 

In [95]:
# Keywords for topics clustered by Latent Dirichlet Allocation
print("LDA Model: \n*", " * "*10)
selected_topics(lda, vectorizer)

LDA Model: 
*  *  *  *  *  *  *  *  *  *  * 
Topic 0:
[('procent', 30.624674334231663), ('ledamot', 15.386927068286438), ('vara', 13.593856342643615), ('utbildning', 12.11211064134661), ('år', 9.42872557395636), ('visa', 5.874137175160997), ('befolkning', 5.858385661645097), ('motsvarande', 5.853490467434753), ('kartläggning', 5.852477157294494), ('låg', 4.766978235031129)]
Topic 1:
[('vara', 187.22097534207526), ('vaccin', 69.65617556993323), ('region', 66.93661833848493), ('sverige', 38.208980860487735), ('vaccinera', 37.97014835599213), ('procent', 35.96177752175765), ('vaccination', 33.22901266475475), ('ta', 33.08853182903713), ('person', 29.321257888611395), ('positiv', 29.02244803077555)]
Topic 2:
[('vara', 187.5571516099634), ('trump', 112.3601060169641), ('president', 84.89895243912353), ('usa', 41.42846600758034), ('donald', 39.43498738783888), ('skriva', 38.27733311433376), ('ta', 36.573447168791844), ('stormning', 36.42786903339943), ('val', 32.460476563066415), ('kapitoliu

### Visualizing LDA results with pyLDAvis

In [96]:
# !pip install pyLDAvis

In [97]:
import pyLDAvis.sklearn
from pylab import bone, pcolor, colorbar, plot, show, rcParams, savefig


In [98]:
pyLDAvis.enable_notebook()
dash = pyLDAvis.sklearn.prepare(lda, data_vectorized, vectorizer, mds='tsne')
dash

PreparedData(topic_coordinates=               x          y  topics  cluster       Freq
topic                                                  
8      32.420952   8.115230       1        1  40.311856
2       0.648955  71.707100       2        1  24.954183
1      71.019684   9.971006       3        1  18.392680
9       3.785981  33.185135       4        1   3.482948
7     -42.666500  -9.222070       5        1   3.334350
3      -3.621689 -43.526516       6        1   3.275023
4      -3.632402  -4.171708       7        1   2.339313
5     -36.584400  35.804413       8        1   2.132221
0      44.391380  50.615383       9        1   1.124583
6      40.235809 -31.591665      10        1   0.652843, topic_info=                    Term        Freq       Total Category  logprob  loglift
961                 vara  905.000000  905.000000  Default  30.0000  30.0000
976                  via  127.000000  127.000000  Default  29.0000  29.0000
651              procent   85.000000   85.000000  Default  28.0000  28.0000
1023                  år  215.000000  215.000000  Default  27.0000  27.0000
888                trump  117.000000  117.000000  Default  26.0000  26.0000
843                   ta  165.000000  165.000000  Default  25.0000  25.0000
986                 visa   79.000000   79.000000  Default  24.0000  24.0000
568                   ny  109.000000  109.000000  Default  23.0000  23.0000
64                  barn   64.000000   64.000000  Default  22.0000  22.0000
32              ansvarig   49.000000   49.000000  Default  21.0000  21.0000
165               drabba   40.000000   40.000000  Default  20.0000  20.0000
815               svensk   62.000000   62.000000  Default  19.0000  19.0000
951               vaccin   76.000000   76.000000  Default  18.0000  18.0000
547                månad   58.000000   58.000000  Default  17.0000  17.0000
667               region   79.000000   79.000000  Default  16.0000  16.0000
461              ledamot   25.000000   25.000000  Default  15.0000  15.0000
816              sverige   72.000000   72.000000  Default  14.0000  14.0000
644            president   91.000000   91.000000  Default  13.0000  13.0000
424             kontakta   33.000000   33.000000  Default  12.0000  12.0000
751               skriva   75.000000   75.000000  Default  11.0000  11.0000
137             december   40.000000   40.000000  Default  10.0000  10.0000
739                själv   57.000000   57.000000  Default   9.0000   9.0000
500                  man   54.000000   54.000000  Default   8.0000   8.0000
941             utgivare   27.000000   27.000000  Default   7.0000   7.0000
328                  hus   36.000000   36.000000  Default   6.0000   6.0000
441                krona   39.000000   39.000000  Default   5.0000   5.0000
676                 resa   36.000000   36.000000  Default   4.0000   4.0000
689                 risk   28.000000   28.000000  Default   3.0000   3.0000
728                  sen   53.000000   53.000000  Default   2.0000   2.0000
785                 stad   39.000000   39.000000  Default   1.0000   1.0000
595              omkomma   33.187491   34.431672   Topic1  -5.4006   0.8717
109                butik   22.682544   24.397492   Topic1  -5.7812   0.8356
25                annons   17.880667   19.431174   Topic1  -6.0191   0.8254
123              cookies   17.895362   19.448453   Topic1  -6.0183   0.8253
243       funktionalitet   17.840508   19.422773   Topic1  -6.0213   0.8235
157                  dom   12.373453   13.566828   Topic1  -6.3872   0.8165
829          säkerställa   19.529923   21.464514   Topic1  -5.9308   0.8141
169                 dygn   13.772660   15.256451   Topic1  -6.2801   0.8062
963               vardag   14.250696   15.796198   Topic1  -6.2460   0.8056
878               tjänst   25.139080   27.940232   Topic1  -5.6784   0.8029
687               riktig    9.867249   11.103934   Topic1  -6.6136   0.7904
521              miljard    9.621899   10.829491   Topic1  -6.6388   0.7903
451              

## Non-Negative Matrix Factorization Model

In [99]:
# Non-Negative Matrix Factorization Model
nmf = NMF(n_components=NUM_TOPICS)  #  solver = 'mu'
data_nmf = nmf.fit_transform(data_vectorized) 


In [100]:
# Keywords for topics clustered by Latent Semantic Indexing
print("NMF Model:\n*" ,' * ' * 10)
selected_topics(nmf, vectorizer)

NMF Model:
*  *  *  *  *  *  *  *  *  *  * 
Topic 0:
[('vara', 9.5260439186314), ('barn', 3.056436038737191), ('stänga', 2.7522515292652727), ('stad', 2.1280242362236197), ('utomhus', 1.7679131952203386), ('ta', 1.663889459175337), ('se', 1.5754233211355222), ('åka', 1.4230636943230766), ('smittspridning', 1.4206551479296416), ('stockholm', 1.3619076393686373)]
Topic 1:
[('vara', 5.037381491277699), ('trump', 2.6610395776013798), ('val', 2.0513388249994504), ('republikan', 1.702778065893477), ('tro', 1.3996775766252794), ('trumps', 1.3956307147763118), ('amerikansk', 1.3827766901955005), ('republikansk', 1.2813105513723337), ('se', 1.2028427800864578), ('makt', 1.0784953235607861)]
Topic 2:
[('vara', 4.2659843828660575), ('vaccin', 2.8002551967851326), ('procent', 1.8968113203094477), ('vaccination', 1.689996251727132), ('vaccinera', 1.6836342664288126), ('region', 1.4450575376513737), ('undersökning', 1.0501828251649494), ('positiv', 0.9988372840712058), ('spak', 0.9982846197340813), 

## Latent Semantic Indexing Model

In [101]:
# Latent Semantic Indexing Model using Truncated SVD
lsi = TruncatedSVD(n_components=NUM_TOPICS)
data_lsi = lsi.fit_transform(data_vectorized)

In [102]:
# Keywords for topics clustered by Non-Negative Matrix Factorization
print("LSI Model:\n*" ,' * ' * 10)
selected_topics(lsi, vectorizer)

LSI Model:
*  *  *  *  *  *  *  *  *  *  * 
Topic 0:
[('vara', 0.814630798424642), ('ta', 0.13924792939205982), ('se', 0.12946287147809157), ('år', 0.12042463886892704), ('barn', 0.10821694537887867), ('stänga', 0.09948263086738954), ('trump', 0.09911133076257705), ('tro', 0.07884465730628203), ('stad', 0.0785704454862601), ('människa', 0.06464008749815452)]
Topic 1:
[('trump', 0.4166762424315463), ('val', 0.22403371464654348), ('republikan', 0.21368208747439857), ('president', 0.21194587586071206), ('trumps', 0.1713015948117791), ('amerikansk', 0.1550042694096991), ('republikansk', 0.15125773470578388), ('makt', 0.11481808903251961), ('ge', 0.11409980638943863), ('januari', 0.11376728940749432)]
Topic 2:
[('barn', 0.25903570862375835), ('stänga', 0.23251570229912458), ('stad', 0.18351032772515102), ('utomhus', 0.1590427061850495), ('åka', 0.12001033765292686), ('smittspridning', 0.100335260375567), ('ungdom', 0.08877080415480235), ('se', 0.07027131673213816), ('människa', 0.0655028460