In [35]:
import numpy as np

#### Prepare Input, Weight and Target for a given imput-to-prediction node transition.

In [36]:
weights = np.array([0,2,1])

In [37]:
weights

array([0, 2, 1])

In [38]:
input_data = np.array([1,2,3])

In [39]:
input_data

array([1, 2, 3])

In [40]:
target = 0

#### Calculate the predictions: preds

In [41]:
preds = (weights * input_data).sum()

In [42]:
preds

7

#### Calculate the error: error

In [43]:
error = preds - target

In [44]:
error

7

#### Calculate the slope: slope 

In [45]:
slope = 2 * input_data * error

In [46]:
slope

array([14, 28, 42])