In [1]:
import numpy as np

### Step 1: Calculate Slop of the loss function w.r.t. value at output node.

#### Prepare Input, Weight and Target for a given imput-to-prediction node transition.

In [2]:
weights = np.array([0,2,1])

In [3]:
weights

array([0, 2, 1])

In [4]:
input_data = np.array([1,2,3])

In [5]:
input_data

array([1, 2, 3])

In [6]:
target = 0

#### Calculate the predictions: preds

In [7]:
preds = (weights * input_data).sum()

In [8]:
preds

7

#### Calculate the error: error

In [9]:
error = preds - target

In [10]:
error

7

#### Calculate the slope: slope 

In [11]:
slope = 2 * input_data * error

In [12]:
slope

array([14, 28, 42])

### Step 2: Update the weight

####  (weights_updated = weights - learning_rate * gradiant or slop)

In [13]:
# Set the learning rate: learning_rate
learning_rate = 0.01

In [16]:
# Update the weights: weights_updated
weights_updated = weights * learning_rate * slope
weights_updated

array([0.  , 0.56, 0.42])

In [17]:
# Get updated predictions: preds_updated
preds_updated = (weights_updated * input_data).sum()
preds_updated

2.38

In [18]:
# Calculate updated error: error_updated
error_updated = preds_updated - target
error_updated

2.38

In [19]:
# Print the original error
print(error)

# Print the updated error
print(error_updated)

7
2.38
