In [21]:
import numpy as np

#### Prepare Input, Weight and Target for a given imput-to-prediction node transition.

In [23]:
weights = np.array([0,2,1])

In [24]:
weights

array([0, 2, 1])

In [25]:
input_data = np.array([1,2,3])

In [26]:
input_data

array([1, 2, 3])

In [27]:
target = 0

#### Calculate the predictions: preds

In [28]:
preds = (weights * input_data).sum()

In [29]:
preds

7

#### Calculate the error: error

In [30]:
error = target - preds

In [31]:
error

-7

#### Calculate the slope: slope 

In [32]:
slope = 2 * input_data * error

In [34]:
slope

array([-14, -28, -42])