In [14]:
import numpy as np

### Numpy.Shape 

In [22]:
arr = "1 2 3 4 5 6 7 8 9".strip().split(' ')
arr2 = list(map(int, arr))

In [23]:
print(np.reshape(arr2 ,(3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Flip array

In [6]:
arr = "1 2 3 4 -8 -10".strip().split(' ')
type(arr)

list

In [8]:
ar = numpy.array(arr,float)
ar2 = numpy.flip(ar)
print(ar2)

[-10.  -8.   4.   3.   2.   1.]


### Concatanation

In [34]:
array_1 = np.array([[1 , 2, 3],
                    [90,90,90]])
array_2 = np.array([[70,70,70],
                    [7 , 8, 9]])

print (np.concatenate((array_1, array_2), axis = 1))

#Output[[1 2 3 0 0 0] [0 0 0 7 8 9]]   

[[ 1  2  3 70 70 70]
 [90 90 90  7  8  9]]


In [35]:
array_3 = np.array([[1,2],
                    [1,2],
                    [1,2],
                    [1,2]])
array_4 = np.array([[3,4],
                    [3,4],
                    [3,4]])

print (np.concatenate((array_3, array_4), axis = 0))


[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### Sum and Prod

In [36]:
my_array = numpy.array([[1, 2], 
                        [3, 4]])

print (numpy.sum(my_array, axis = 0))         #Output : [4 6]
print (numpy.sum(my_array, axis = 1))         #Output : [3 7]
print (numpy.sum(my_array, axis = None))      #Output : 10

# By default, the axis value is None. Therefore, it performs a sum over all the dimensions of the input array.
print (numpy.sum(my_array))                   #Output : 10

[4 6]
[3 7]
10
10


In [37]:
my_array = numpy.array([ [1, 2], [3, 4] ])

print (numpy.prod(my_array, axis = 0))            #Output : [3 8]
print (numpy.prod(my_array, axis = 1))            #Output : [ 2 12]
print (numpy.prod(my_array, axis = None))         #Output : 24
print (numpy.prod(my_array))                      #Output : 24

[3 8]
[ 2 12]
24
24


### Array

In [40]:
x = [5,1,7,0,3,4]
print(x.index(7))

2


In [53]:
x = [5,1,7,0,3,4,5,3,2,6,7,3,6]
get_indexes = lambda x, xs: [i for (y, i) in zip(xs, range(len(xs))) if x == y]
print(get_indexes(3,x))

[4, 7, 11]


In [50]:
x = []
for i in range(2,5+1):
    if (i % 2):
        print('Odd ',i)
        x.append(i)
    else:
        print('Even ',i)

        
print(x)

Even  2
Odd  3
Even  4
Odd  5
[3, 5]


In [56]:
from itertools import permutations

In [58]:
print (permutations(['1','2','3']))

In [59]:
print (list(permutations(['1','2','3'])))

[('1', '2', '3'), ('1', '3', '2'), ('2', '1', '3'), ('2', '3', '1'), ('3', '1', '2'), ('3', '2', '1')]


In [60]:
print (list(permutations(['1','2','3'],2)))

[('1', '2'), ('1', '3'), ('2', '1'), ('2', '3'), ('3', '1'), ('3', '2')]


In [73]:
print (list(permutations('ABCDEFGHIJKLMNOPQRSTUVWXYZ',2)))

[('A', 'B'), ('A', 'C'), ('A', 'D'), ('A', 'E'), ('A', 'F'), ('A', 'G'), ('A', 'H'), ('A', 'I'), ('A', 'J'), ('A', 'K'), ('A', 'L'), ('A', 'M'), ('A', 'N'), ('A', 'O'), ('A', 'P'), ('A', 'Q'), ('A', 'R'), ('A', 'S'), ('A', 'T'), ('A', 'U'), ('A', 'V'), ('A', 'W'), ('A', 'X'), ('A', 'Y'), ('A', 'Z'), ('B', 'A'), ('B', 'C'), ('B', 'D'), ('B', 'E'), ('B', 'F'), ('B', 'G'), ('B', 'H'), ('B', 'I'), ('B', 'J'), ('B', 'K'), ('B', 'L'), ('B', 'M'), ('B', 'N'), ('B', 'O'), ('B', 'P'), ('B', 'Q'), ('B', 'R'), ('B', 'S'), ('B', 'T'), ('B', 'U'), ('B', 'V'), ('B', 'W'), ('B', 'X'), ('B', 'Y'), ('B', 'Z'), ('C', 'A'), ('C', 'B'), ('C', 'D'), ('C', 'E'), ('C', 'F'), ('C', 'G'), ('C', 'H'), ('C', 'I'), ('C', 'J'), ('C', 'K'), ('C', 'L'), ('C', 'M'), ('C', 'N'), ('C', 'O'), ('C', 'P'), ('C', 'Q'), ('C', 'R'), ('C', 'S'), ('C', 'T'), ('C', 'U'), ('C', 'V'), ('C', 'W'), ('C', 'X'), ('C', 'Y'), ('C', 'Z'), ('D', 'A'), ('D', 'B'), ('D', 'C'), ('D', 'E'), ('D', 'F'), ('D', 'G'), ('D', 'H'), ('D', 'I'), ('D

In [67]:

class A 
{}
class B extends A
{}

SyntaxError: invalid syntax (<ipython-input-67-cb9087a410a8>, line 2)

In [4]:
col0 = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
col1 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
col2 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
st= col1[3]+col1[3]
st

'DD'

In [5]:
col = []
for x in col1:
    for y in col1:
#         print(x,y)
        col.append(x+y)

columns = col0+col
len(columns)

702

In [6]:
import pandas as pd
df = pd.DataFrame(columns=columns)


In [7]:
df

Empty DataFrame
Columns: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, AH, AI, AJ, AK, AL, AM, AN, AO, AP, AQ, AR, AS, AT, AU, AV, AW, AX, AY, AZ, BA, BB, BC, BD, BE, BF, BG, BH, BI, BJ, BK, BL, BM, BN, BO, BP, BQ, BR, BS, BT, BU, BV, BW, BX, BY, BZ, CA, CB, CC, CD, CE, CF, CG, CH, CI, CJ, CK, CL, CM, CN, CO, CP, CQ, CR, CS, CT, CU, CV, ...]
Index: []

[0 rows x 702 columns]

In [8]:

# df.append(range(0,701))
df.loc[0]=[x for x in range(1,703)]

In [9]:
df

A  B  C  D  E  F  G  H  I   J ...    ZQ   ZR   ZS   ZT   ZU   ZV   ZW   ZX  \
0  1  2  3  4  5  6  7  8  9  10 ...   693  694  695  696  697  698  699  700   

    ZY   ZZ  
0  701  702  

[1 rows x 702 columns]

In [10]:
df.loc[1]=[x for x in range(703,703+702)]

In [11]:
df

A    B    C    D    E    F    G    H    I    J  ...     ZQ    ZR    ZS  \
0    1    2    3    4    5    6    7    8    9   10  ...    693   694   695   
1  703  704  705  706  707  708  709  710  711  712  ...   1395  1396  1397   

     ZT    ZU    ZV    ZW    ZX    ZY    ZZ  
0   696   697   698   699   700   701   702  
1  1398  1399  1400  1401  1402  1403  1404  

[2 rows x 702 columns]

In [12]:
for row in range(100):
    df.loc[row]=[x for x in range((row * 702) + 1, (row * 702 + 1) + 702)]


    
    
    
    

In [13]:
df

A      B      C      D      E      F      G      H      I      J  \
0       1      2      3      4      5      6      7      8      9     10   
1     703    704    705    706    707    708    709    710    711    712   
2    1405   1406   1407   1408   1409   1410   1411   1412   1413   1414   
3    2107   2108   2109   2110   2111   2112   2113   2114   2115   2116   
4    2809   2810   2811   2812   2813   2814   2815   2816   2817   2818   
5    3511   3512   3513   3514   3515   3516   3517   3518   3519   3520   
6    4213   4214   4215   4216   4217   4218   4219   4220   4221   4222   
7    4915   4916   4917   4918   4919   4920   4921   4922   4923   4924   
8    5617   5618   5619   5620   5621   5622   5623   5624   5625   5626   
9    6319   6320   6321   6322   6323   6324   6325   6326   6327   6328   
10   7021   7022   7023   7024   7025   7026   7027   7028   7029   7030   
11   7723   7724   7725   7726   7727   7728   7729   7730   7731   7732   
12   8425   8426   8427   8428   8429   8430   8431   8432   8433   8434   
13   9127   9128   9129   9130   9131   9132   9133   9134   9135   9136   
14   9829   9830   9831   9832   9833   9834   9835   9836   9837   9838   
15  10531  10532  10533  10534  10535  10536  10537  10538  10539  10540   
16  11233  11234  11235  11236  11237  11238  11239  11240  11241  11242   
17  11935  11936  11937  11938  11939  11940  11941  11942  11943  11944   
18  12637  12638  12639  12640  12641  12642  12643  12644  12645  12646   
19  13339  13340  13341  13342  13343  13344  13345  13346  13347  13348   
20  14041  14042  14043  14044  14045  14046  14047  14048  14049  14050   
21  14743  14744  14745  14746  14747  14748  14749  14750  14751  14752   
22  15445  15446  15447  15448  15449  15450  15451  15452  15453  15454   
23  16147  16148  16149  16150  16151  16152  16153  16154  16155  16156   
24  16849  16850  16851  16852  16853  16854  16855  16856  16857  16858   
25  17551  17552  17553  17554  17555  17556  17557  17558  17559  17560   
26  18253  18254  18255  18256  18257  18258  18259  18260  18261  18262   
27  18955  18956  18957  18958  18959  18960  18961  18962  18963  18964   
28  19657  19658  19659  19660  19661  19662  19663  19664  19665  19666   
29  20359  20360  20361  20362  20363  20364  20365  20366  20367  20368   
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
70  49141  49142  49143  49144  49145  49146  49147  49148  49149  49150   
71  49843  49844  49845  49846  49847  49848  49849  49850  49851  49852   
72  50545  50546  50547  50548  50549  50550  50551  50552  50553  50554   
73  51247  51248  51249  51250  51251  51252  51253  51254  51255  51256   
74  51949  51950  51951  51952  51953  51954  51955  51956  51957  51958   
75  52651  52652  52653  52654  52655  52656  52657  52658  52659  52660   
76  53353  53354  53355  53356  53357  53358  53359  53360  53361  53362   
77  54055  54056  54057  54058  54059  54060  54061  54062  54063  54064   
78  54757  54758  54759  54760  54761  54762  54763  54764  54765  54766   
79  55459  55460  55461  55462  55463  55464  55465  55466  55467  55468   
80  56161  56162  56163  56164  56165  56166  56167  56168  56169  56170   
81  56863  56864  56865  56866  56867  56868  56869  56870  56871  56872   
82  57565  57566  57567  57568  57569  57570  57571  57572  57573  57574   
83  58267  58268  58269  58270  58271  58272  58273  58274  58275  58276   
84  58969  58970  58971  58972  58973  58974  58975  58976  58977  58978   
85  59671  59672  59673  59674  59675  59676  59677  59678  59679  59680   
86  60373  60374  60375  60376  60377  60378  60379  60380  60381  60382   
87  61075  61076  61077  61078  61079  61080  61081  61082  61083  61084   
88  61777  61778  61779  61780  61781  61782  61783  61784  61785  61786   
89  62479  62480  62481  62482  62483  62484  62485  62486  62487  62488   
90  63181  63182  63183  63184  63185  63186  63187  631

In [14]:
ind = df[(df == 2222).any(1)].index # stack() # [lambda x: x == 2222].unique()

In [15]:
ind[0]

3

In [16]:
res = df[(df == 2222).any(1)].stack()[lambda x: x == 2222]

In [17]:
res

3  DL    2222
dtype: int64

In [18]:
tpl = res.index[0]
str1 = str(int(tpl[0])) + tpl[1]
#print(tpl[1])
str1

'3DL'

In [209]:
dfRes = pd.DataFrame(res)

In [214]:
dfRes[0]

3  DL    2222
Name: 0, dtype: int64