In [4]:
#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [5]:
import numpy as np 
# 3 training data and 4 features (matrix of R^3X4)
X=np.array([[1, 0, 1, 0],
            [1, 0, 1, 1],
            [0, 1, 0, 1]])
X.shape
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [6]:
# weight matrix for input(4neurons) to hidden-layer(3neurons) (R^4X3)
wh = np.array([[.42,.88,.55],
               [.10,.73,.68],
               [.60,.18,.47],
               [.92,.11,.52]])
wh.shape
wh


array([[ 0.42,  0.88,  0.55],
       [ 0.1 ,  0.73,  0.68],
       [ 0.6 ,  0.18,  0.47],
       [ 0.92,  0.11,  0.52]])

In [7]:
#The byas
bh = np.array([.46,.72,.08])
bh

array([ 0.46,  0.72,  0.08])

In [8]:
#Calculating activation-input by matrix multiplication (input_matrix X weight_matrix) 
Z=np.dot(X,wh) + bh
Z

array([[ 1.48,  1.78,  1.1 ],
       [ 2.4 ,  1.89,  1.62],
       [ 1.48,  1.56,  1.28]])

In [9]:
#Calculating activation with the hypothesis of Sigmoid function 
Act = sigmoid(Z)
Act = Act
Act
#Act.shape

array([[ 0.81457258,  0.85569687,  0.75026011],
       [ 0.9168273 ,  0.86875553,  0.83479513],
       [ 0.81457258,  0.82635335,  0.78244978]])

In [10]:
#Waits for hidden-layer to output-layer (R^1x3)
wh_1_2 = np.array([[ 0.3,  0.25,  0.23]]).T
wh_1_2
#wh_1_2.shape

array([[ 0.3 ],
       [ 0.25],
       [ 0.23]])

In [11]:
#Calculate the outputs vector
bh_1_2 = 0.69
Output_layer_input = np.dot( Act, wh_1_2) + bh_1_2
Output = sigmoid(Output_layer_input)
Output

array([[ 0.78932406],
       [ 0.79806432],
       [ 0.78933532]])

In [13]:
Y = np.array([[1,1,0]])
Y = Y.T
Y

array([[1],
       [1],
       [0]])

In [14]:
E = Y - Output
E

array([[ 0.21067594],
       [ 0.20193568],
       [-0.78933532]])