In [33]:
#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [28]:
import numpy as np
X=np.array([[1],
            [0],
            [1],
            [0]]).T
X.shape

(1, 4)

In [29]:
wh = np.array([[.42,.88,.55],
               [.10,.73,.68],
               [.60,.18,.47],
               [.92,.11,.52]])
wh.shape

(4, 3)

In [30]:
bh = np.array([.46,.72,.08])
bh

array([ 0.46,  0.72,  0.08])

In [31]:
Z=np.dot(X,wh) + bh
Z

array([[ 1.48,  1.78,  1.1 ]])

In [43]:
Act = sigmoid(Z)
Act
#Act.shape

array([[ 0.81457258,  0.85569687,  0.75026011]])

In [41]:
wh_1_2 = np.array([[ 0.3,  0.25,  0.23]]).T
wh_1_2
#wh_1_2.shape

array([[ 0.3 ],
       [ 0.25],
       [ 0.23]])

In [46]:
bh_1_2 = 0.69
Output_layer_input = np.dot( Act, wh_1_2) + bh_1_2
Output = sigmoid(Output_layer_input)
Output

array([[ 0.78932406]])