### Upgrage numpy

!pip install numpy --upgrade

In [3]:
import numpy as np

### Array Handling


In [114]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [93]:
print('First element %i' %a[0])
print('Last element %i' %a[-1])
print('Second to last element %i' %a[-2])
print('A slice indx 1 to 3: ', a[1:4])
print('A slice indx 1 to 4 FROM LAST: ', a[1:-4])



First element 1
Last element 9
Second to last element 8
A slice indx 1 to 3:  [2 3 4]
A slice indx 1 to 4 FROM LAST:  [2 3 4 5]


In [69]:
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [71]:
a.sum()

20

In [73]:
a.mean()

4.0

#### Split in equal portion 

In [115]:

np.split(a,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

#### Split at indexes 

In [116]:
np.split(a,[2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

#### Converting python list to Numpy array

In [111]:
numbers = [2,3,4,5,6]
a = np.array(numbers)
print(a)

[2 3 4 5 6]


### Matrix operations

In [11]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [5]:
a = np.array([(2,3,4),(5,6,7),(8,9,1),(2,3,4)])
print(a)

[[2 3 4]
 [5 6 7]
 [8 9 1]
 [2 3 4]]


In [7]:
# Print a row
print(a[1])
print(a[3])

[5 6 7]
[2 3 4]


In [8]:
# Print an element
print(a[1,2])

7


In [10]:
# Print rows 0:2 and column 1:3
print(a[0:2,1:3])

[[3 4]
 [6 7]]


In [11]:
# Print columns first two colomns ie. 0:2
print(a[:,0:2])


[[2 3]
 [5 6]
 [8 9]
 [2 3]]


In [12]:
# Print last first three rows ie. 0:3
print(a[0:3,:])

[[2 3 4]
 [5 6 7]
 [8 9 1]]


In [13]:
# Print last two rows
print(a[-2:,:])

[[8 9 1]
 [2 3 4]]


In [130]:
a = np.array([[2,3,4],[5,6,7]])
a

array([[2, 3, 4],
       [5, 6, 7]])

In [129]:
print(a)
print(a.shape)
print('Reshape the 2D array')
print(a.reshape(3,2))

(2, 3)
Reshape the 2D array
[[2 3]
 [4 5]
 [6 7]]


In [131]:
a.shape

(2, 3)

In [139]:
p1, p2 = np.vsplit(a,2)
print(p1)
print(p2)

[[2 3 4]
 [5 6 7]]
[[8 9 1]
 [2 3 4]]


### Element wise operation(add,multiply...) or scelar operation

In [48]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [54]:
a = np.array([[10,20,30],
              [40,50,60]])
b = np.array([[1,2,3],
              [4,5,5]])
print('A:\n',a)
print('B:\n',b)

A:
 [[10 20 30]
 [40 50 60]]
B:
 [[1 2 3]
 [4 5 5]]


In [55]:
a*b

array([[ 10,  40,  90],
       [160, 250, 300]])

In [56]:
np.multiply(a,b)

array([[ 10,  40,  90],
       [160, 250, 300]])

### Dot operation or matrix operation 
#### To do such operation between matrix mxn and mxn we need to transpose one of the metrix to make nxm.

In [61]:
a

array([[10, 20, 30],
       [40, 50, 60]])

#### Transpose 

In [62]:
b.T

array([[1, 4],
       [2, 5],
       [3, 5]])

In [63]:
a.dot(b.T)

array([[140, 290],
       [320, 710]])

In [64]:
np.dot(a, b.T)

array([[140, 290],
       [320, 710]])

In [65]:
a.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [66]:
b

array([[1, 2, 3],
       [4, 5, 5]])

In [67]:
np.dot(a.T, b)

array([[170, 220, 230],
       [220, 290, 310],
       [270, 360, 390]])

In [68]:
a.T.dot(b)

array([[170, 220, 230],
       [220, 290, 310],
       [270, 360, 390]])

## Function Vectorization

In [15]:
def addOrSubstruct(a,b):
    "If a>b return a-b else a+b"
    if (a>b):
        return a-b
    else:
        return a+b

In [19]:
addOrSubstruct(5,10)

15

In [16]:
# Now vertorize to make scaler product
vect_addOrSubstruct = np.vectorize(addOrSubstruct)

In [18]:
vect_addOrSubstruct([2,5,10],[6,3,5])

array([8, 2, 5])