### Upgrage numpy

!pip install numpy --upgrade

In [4]:
import numpy as np

### Array Handling


In [114]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [93]:
print('First element %i' %a[0])
print('Last element %i' %a[-1])
print('Second to last element %i' %a[-2])
print('A slice indx 1 to 3: ', a[1:4])
print('A slice indx 1 to 4 FROM LAST: ', a[1:-4])



First element 1
Last element 9
Second to last element 8
A slice indx 1 to 3:  [2 3 4]
A slice indx 1 to 4 FROM LAST:  [2 3 4 5]


In [69]:
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [71]:
a.sum()

20

In [73]:
a.mean()

4.0

#### Split in equal portion 

In [115]:

np.split(a,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

#### Split at indexes 

In [116]:
np.split(a,[2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

#### Converting python list to Numpy array

In [111]:
numbers = [2,3,4,5,6]
a = np.array(numbers)
print(a)

[2 3 4 5 6]


### Matrix operations

In [11]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [138]:
a = np.array([(2,3,4),(5,6,7),(8,9,1),(2,3,4)])
print(a)

[[2 3 4]
 [5 6 7]
 [8 9 1]
 [2 3 4]]


In [130]:
a = np.array([[2,3,4],[5,6,7]])
a

array([[2, 3, 4],
       [5, 6, 7]])

In [129]:
print(a)
print(a.shape)
print('Reshape the 2D array')
print(a.reshape(3,2))

(2, 3)
Reshape the 2D array
[[2 3]
 [4 5]
 [6 7]]


In [131]:
a.shape

(2, 3)

In [139]:
p1, p2 = np.vsplit(a,2)
print(p1)
print(p2)

[[2 3 4]
 [5 6 7]]
[[8 9 1]
 [2 3 4]]


### Element wise operation(add,multiply...) or scelar operation

In [48]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [54]:
a = np.array([[10,20,30],
              [40,50,60]])
b = np.array([[1,2,3],
              [4,5,5]])
print('A:\n',a)
print('B:\n',b)

A:
 [[10 20 30]
 [40 50 60]]
B:
 [[1 2 3]
 [4 5 5]]


In [55]:
a*b

array([[ 10,  40,  90],
       [160, 250, 300]])

In [56]:
np.multiply(a,b)

array([[ 10,  40,  90],
       [160, 250, 300]])

### Dot operation or matrix operation 
#### To do such operation between matrix mxn and mxn we need to transpose one of the metrix to make nxm.

In [61]:
a

array([[10, 20, 30],
       [40, 50, 60]])

#### Transpose 

In [62]:
b.T

array([[1, 4],
       [2, 5],
       [3, 5]])

In [63]:
a.dot(b.T)

array([[140, 290],
       [320, 710]])

In [64]:
np.dot(a, b.T)

array([[140, 290],
       [320, 710]])

In [65]:
a.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [66]:
b

array([[1, 2, 3],
       [4, 5, 5]])

In [67]:
np.dot(a.T, b)

array([[170, 220, 230],
       [220, 290, 310],
       [270, 360, 390]])

In [68]:
a.T.dot(b)

array([[170, 220, 230],
       [220, 290, 310],
       [270, 360, 390]])

## Read from file


In [107]:
data = np.genfromtxt('data/iris.txt', delimiter=',',dtype=( float, float, float, float, '|U8'))
print(data)

[( 5.1,  7. ,   2.8,  0.6, 'Iris-set')
 ( 4.9,  6. ,   2.8,  0.6, 'Iris-set')
 ( 4.7,  6.4,   2.6,  0.6, 'Iris-set')
 ( 4.6,  6.2,   3. ,  0.6, 'Iris-set')
 ( 5. ,  7.2,   2.8,  0.6, 'Iris-set')
 ( 5.4,  7.8,   3.4,  1.2, 'Iris-set')
 ( 4.6,  6.8,   2.8,  0.9, 'Iris-set')
 ( 5. ,  6.8,   3. ,  0.6, 'Iris-set')
 ( 4.4,  5.8,   2.8,  0.6, 'Iris-set')
 ( 4.9,  6.2,   3. ,  0.3, 'Iris-set')
 ( 5.4,  7.4,   3. ,  0.6, 'Iris-set')
 ( 4.8,  6.8,   3.2,  0.6, 'Iris-set')
 ( 4.8,  6. ,   2.8,  0.3, 'Iris-set')
 ( 4.3,  6. ,   2.2,  0.3, 'Iris-set')
 ( 5.8,  8. ,   2.4,  0.6, 'Iris-set')
 ( 5.7,  8.8,   3. ,  1.2, 'Iris-set')
 ( 5.4,  7.8,   2.6,  1.2, 'Iris-set')
 ( 5.1,  7. ,   2.8,  0.9, 'Iris-set')
 ( 5.7,  7.6,   3.4,  0.9, 'Iris-set')
 ( 5.1,  7.6,   3. ,  0.9, 'Iris-set')
 ( 5.4,  6.8,   3.4,  0.6, 'Iris-set')
 ( 5.1,  7.4,   3. ,  1.2, 'Iris-set')
 ( 4.6,  7.2,   2. ,  0.6, 'Iris-set')
 ( 5.1,  6.6,   3.4,  1.5, 'Iris-set')
 ( 4.8,  6.8,   3.8,  0.6, 'Iris-set')
 ( 5. ,  6. ,   3.2,  0.6

In [80]:
print('There are %i samples in the file' %data.shape[0])

There are 105 samples in the file


### Iterate all the rows

In [103]:
for i in data:
    print('r = ', i)

r =  [ 5.1  7.   2.8  0.6  nan]
r =  [ 4.9  6.   2.8  0.6  nan]
r =  [ 4.7  6.4  2.6  0.6  nan]
r =  [ 4.6  6.2  3.   0.6  nan]
r =  [ 5.   7.2  2.8  0.6  nan]
r =  [ 5.4  7.8  3.4  1.2  nan]
r =  [ 4.6  6.8  2.8  0.9  nan]
r =  [ 5.   6.8  3.   0.6  nan]
r =  [ 4.4  5.8  2.8  0.6  nan]
r =  [ 4.9  6.2  3.   0.3  nan]
r =  [ 5.4  7.4  3.   0.6  nan]
r =  [ 4.8  6.8  3.2  0.6  nan]
r =  [ 4.8  6.   2.8  0.3  nan]
r =  [ 4.3  6.   2.2  0.3  nan]
r =  [ 5.8  8.   2.4  0.6  nan]
r =  [ 5.7  8.8  3.   1.2  nan]
r =  [ 5.4  7.8  2.6  1.2  nan]
r =  [ 5.1  7.   2.8  0.9  nan]
r =  [ 5.7  7.6  3.4  0.9  nan]
r =  [ 5.1  7.6  3.   0.9  nan]
r =  [ 5.4  6.8  3.4  0.6  nan]
r =  [ 5.1  7.4  3.   1.2  nan]
r =  [ 4.6  7.2  2.   0.6  nan]
r =  [ 5.1  6.6  3.4  1.5  nan]
r =  [ 4.8  6.8  3.8  0.6  nan]
r =  [ 5.   6.   3.2  0.6  nan]
r =  [ 5.   6.8  3.2  1.2  nan]
r =  [ 5.2  7.   3.   0.6  nan]
r =  [ 5.2  6.8  2.8  0.6  nan]
r =  [ 4.7  6.4  3.2  0.6  nan]
r =  [ 4.8  6.2  3.2  0.6  nan]
r =  [ 5

### Get all the elements individually 

In [101]:
for i in data.flatten():
    print('element = ', i)

element =  5.1
element =  7.0
element =  2.8
element =  0.6
element =  nan
element =  4.9
element =  6.0
element =  2.8
element =  0.6
element =  nan
element =  4.7
element =  6.4
element =  2.6
element =  0.6
element =  nan
element =  4.6
element =  6.2
element =  3.0
element =  0.6
element =  nan
element =  5.0
element =  7.2
element =  2.8
element =  0.6
element =  nan
element =  5.4
element =  7.8
element =  3.4
element =  1.2
element =  nan
element =  4.6
element =  6.8
element =  2.8
element =  0.9
element =  nan
element =  5.0
element =  6.8
element =  3.0
element =  0.6
element =  nan
element =  4.4
element =  5.8
element =  2.8
element =  0.6
element =  nan
element =  4.9
element =  6.2
element =  3.0
element =  0.3
element =  nan
element =  5.4
element =  7.4
element =  3.0
element =  0.6
element =  nan
element =  4.8
element =  6.8
element =  3.2
element =  0.6
element =  nan
element =  4.8
element =  6.0
element =  2.8
element =  0.3
element =  nan
element =  4.3
element = 

In [102]:
for i in data.flatten(order='F'):
    print('element = ', i)

element =  5.1
element =  4.9
element =  4.7
element =  4.6
element =  5.0
element =  5.4
element =  4.6
element =  5.0
element =  4.4
element =  4.9
element =  5.4
element =  4.8
element =  4.8
element =  4.3
element =  5.8
element =  5.7
element =  5.4
element =  5.1
element =  5.7
element =  5.1
element =  5.4
element =  5.1
element =  4.6
element =  5.1
element =  4.8
element =  5.0
element =  5.0
element =  5.2
element =  5.2
element =  4.7
element =  4.8
element =  5.4
element =  5.2
element =  5.5
element =  4.9
element =  5.0
element =  5.5
element =  4.9
element =  4.4
element =  5.1
element =  5.0
element =  4.5
element =  4.4
element =  5.0
element =  5.1
element =  4.8
element =  5.1
element =  4.6
element =  5.3
element =  5.0
element =  7.0
element =  6.4
element =  6.9
element =  5.5
element =  6.5
element =  5.7
element =  6.3
element =  4.9
element =  6.6
element =  5.2
element =  5.0
element =  5.9
element =  6.0
element =  6.1
element =  5.6
element =  6.7
element = 